/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 michelle1.glb --transform 
Files: michelle1.glb [22.01MB] > /home/matheus/Downloads/michelle1-transformed.glb [553.81KB] (97%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

const Michelle = (props) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/michelle1-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.music.play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} position={[0, -3.5, 0]} scale={0.0355}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh
          name="Ch03"
          geometry={nodes.Ch03.geometry}
          material={materials.Ch03_Body}
          skeleton={nodes.Ch03.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.1}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/michelle1-transformed.glb");

export default Michelle;
