/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

const sequence = [
  "idle",
  "Greeting",
  "armStretch",
  "music",
  "lookOverShoulder",
];

const Michelle = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/michelle.glb");
  const { actions } = useAnimations(animations, group);
  const [currentAction, setCurrentAction] = useState(null);
  const [step, setStep] = useState(0);

  const playAction = (name, fadeDuration = 1) => {
    if (!actions[name]) {
      console.warn(`Action ${name} not found`);
      return;
    }

   
    if (currentAction && actions[currentAction]) {
      actions[currentAction].fadeOut(fadeDuration);
    }

    actions[name].reset().fadeIn(fadeDuration).play();
    setCurrentAction(name);
  };

  useEffect(() => {
    if (!actions) return;

    let timeoutId;

    const runSequence = () => {
      const nextAction = sequence[step % sequence.length];
      playAction(nextAction);

      const duration = actions[nextAction]?._clip?.duration || 3;
      const extraHold = nextAction === "music" ? 5 : 0;

      timeoutId = setTimeout(() => {
        setStep((prev) => prev + 1);
      }, (duration + extraHold + 0.5) * 1000);
    };

    runSequence();

    return () => clearTimeout(timeoutId);
  }, [actions, step]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          rotation={[Math.PI / 1.8, 0, 0]}
          position={[0, -3.5, 0]}
          scale={0.0355}
        >
          <skinnedMesh
            name="Ch03"
            geometry={nodes.Ch03.geometry}
            material={materials.Ch03_Body}
            skeleton={nodes.Ch03.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/michelle.glb");
export default Michelle;
